-- This file is for use with Corona Game Edition
-- 
-- The function getSpriteSheetData() returns a table suitable for importing using sprite.newSpriteSheetFromData()
-- 
-- This file is automatically generated with TexturePacker (http://texturepacker.com). Do not edit
-- $TexturePacker:SmartUpdate:cbf8be8ad299b4aba63dabe2b5541412$
-- 
-- Usage example:
--        local sheetData = require "ThisFile.lua"
--        local data = sheetData.getSpriteSheetData()
--        local spriteSheet = sprite.newSpriteSheetFromData( "Untitled.png", data )
-- 
-- For more details, see http://developer.anscamobile.com/content/game-edition-sprite-sheets

local SpriteSheet = {}
SpriteSheet.getSpriteSheetData = function ()
	return {
		frames = {
			{
				name = "paddle0000.png",
				spriteColorRect = { x = 0, y = 0, width = 128, height = 32 },
				textureRect = { x = 262, y = 70, width = 128, height = 32 },
				spriteSourceSize = { width = 128, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "paddle0001.png",
				spriteColorRect = { x = 0, y = 0, width = 128, height = 32 },
				textureRect = { x = 132, y = 70, width = 128, height = 32 },
				spriteSourceSize = { width = 128, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "paddle0002.png",
				spriteColorRect = { x = 0, y = 0, width = 128, height = 32 },
				textureRect = { x = 2, y = 70, width = 128, height = 32 },
				spriteSourceSize = { width = 128, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "paddle0003.png",
				spriteColorRect = { x = 0, y = 0, width = 128, height = 32 },
				textureRect = { x = 262, y = 36, width = 128, height = 32 },
				spriteSourceSize = { width = 128, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "paddle0004.png",
				spriteColorRect = { x = 0, y = 0, width = 128, height = 32 },
				textureRect = { x = 132, y = 36, width = 128, height = 32 },
				spriteSourceSize = { width = 128, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "paddle0005.png",
				spriteColorRect = { x = 0, y = 0, width = 128, height = 32 },
				textureRect = { x = 2, y = 36, width = 128, height = 32 },
				spriteSourceSize = { width = 128, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "paddle0006.png",
				spriteColorRect = { x = 0, y = 0, width = 128, height = 32 },
				textureRect = { x = 262, y = 2, width = 128, height = 32 },
				spriteSourceSize = { width = 128, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "paddle0007.png",
				spriteColorRect = { x = 0, y = 0, width = 128, height = 32 },
				textureRect = { x = 132, y = 2, width = 128, height = 32 },
				spriteSourceSize = { width = 128, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "paddle0008.png",
				spriteColorRect = { x = 0, y = 0, width = 128, height = 32 },
				textureRect = { x = 2, y = 2, width = 128, height = 32 },
				spriteSourceSize = { width = 128, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
		}
	}
end
return SpriteSheet

