-- This file is for use with Corona Game Edition
-- 
-- The function getSpriteSheetData() returns a table suitable for importing using sprite.newSpriteSheetFromData()
-- 
-- This file is automatically generated with TexturePacker (http://texturepacker.com). Do not edit
-- $TexturePacker:SmartUpdate:3434c9431a24ddcfc6e337e8dedf0336$
-- 
-- Usage example:
--        local sheetData = require "ThisFile.lua"
--        local data = sheetData.getSpriteSheetData()
--        local spriteSheet = sprite.newSpriteSheetFromData( "Untitled.png", data )
-- 
-- For more details, see http://developer.anscamobile.com/content/game-edition-sprite-sheets

local SpriteSheet = {}
SpriteSheet.getSpriteSheetData = function ()
	return {
		frames = {
			{
				name = "Untitled-10000.png",
				spriteColorRect = { x = 0, y = 0, width = 40, height = 20 },
				textureRect = { x = 2, y = 2, width = 40, height = 20 },
				spriteSourceSize = { width = 40, height = 20 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Untitled-10001.png",
				spriteColorRect = { x = 0, y = 0, width = 40, height = 20 },
				textureRect = { x = 44, y = 2, width = 40, height = 20 },
				spriteSourceSize = { width = 40, height = 20 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Untitled-10002.png",
				spriteColorRect = { x = 0, y = 0, width = 40, height = 20 },
				textureRect = { x = 86, y = 2, width = 40, height = 20 },
				spriteSourceSize = { width = 40, height = 20 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Untitled-10003.png",
				spriteColorRect = { x = 0, y = 0, width = 40, height = 20 },
				textureRect = { x = 2, y = 24, width = 40, height = 20 },
				spriteSourceSize = { width = 40, height = 20 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Untitled-10004.png",
				spriteColorRect = { x = 0, y = 0, width = 40, height = 20 },
				textureRect = { x = 44, y = 24, width = 40, height = 20 },
				spriteSourceSize = { width = 40, height = 20 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Untitled-10005.png",
				spriteColorRect = { x = 0, y = 0, width = 40, height = 20 },
				textureRect = { x = 86, y = 24, width = 40, height = 20 },
				spriteSourceSize = { width = 40, height = 20 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Untitled-10006.png",
				spriteColorRect = { x = 0, y = 0, width = 40, height = 20 },
				textureRect = { x = 2, y = 46, width = 40, height = 20 },
				spriteSourceSize = { width = 40, height = 20 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Untitled-10007.png",
				spriteColorRect = { x = 0, y = 0, width = 40, height = 20 },
				textureRect = { x = 44, y = 46, width = 40, height = 20 },
				spriteSourceSize = { width = 40, height = 20 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Untitled-10008.png",
				spriteColorRect = { x = 0, y = 0, width = 0, height = 0 },
				textureRect = { x = 86, y = 46, width = 0, height = 0 },
				spriteSourceSize = { width = 40, height = 20 },
				spriteTrimmed = false,
				textureRotated = false
			},
		}
	}
end
return SpriteSheet

